wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714192057.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.12.0
      5: 0.16.6
      6: 4.40.1
      8:
      - 3
      - 5
      13: windows-amd64
